version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./app:/app
      - ./data:/app
    environment:
      - SECRET_KEY=changeme
    depends_on:
      - authelia
    networks:
      - net

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - authelia
    networks:
      - net

  authelia:
    image: authelia/authelia:latest
    volumes:
      - ./authelia:/config
    networks:
      - net
volumes:
  data:
networks:
  net:
