log:
  level: info

server:
  address: tcp://0.0.0.0:9091

identity_validation:
  reset_password:
    jwt_secret: changeme

default_redirection_url: http://localhost/

access_control:
  default_policy: deny
  rules:
    - domain: localhost
      policy: bypass

session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  same_site: lax
  domain: localhost

storage:
  encryption_key: changemechangemechangemechangeme
  local:
    path: /config/db.sqlite3

authentication_backend:
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id

notifier:
  filesystem:
    filename: /config/notification.txt
